name = "cf-proxy-gateway"
main = "src/index.ts"
compatibility_date = "2025-05-01"
compatibility_flags = ["nodejs_compat"]

usage_model = "bundled"

[vars]
ENV = "production"
DEBUG = "false"
LOG_LEVEL = "info"
